import { Category, Document } from './types';

export const CATEGORIES: Category[] = [
    { id: 'cat1', nameKey: 'categories.armoplit' },
    { id: 'cat2', nameKey: 'categories.edilmodulo' },
    { id: 'cat3', nameKey: 'categories.fixit' },
    { id: 'cat4', nameKey: 'categories.freudenberg' },
    { id: 'cat5', nameKey: 'categories.typar' },
];

export const RECENT_DOCUMENTS: Document[] = [
    {
        id: 'doc1',
        title: 'Висновок СЕЕ на Цементно-стружкові плити ArmoPlit. 2023-2028',
        categoryKey: 'categories.armoplit',
        updatedAt: new Date('2023-10-26'),
        tags: ['Висновок СЕЕ', 'ArmoPlit'],
        content: { en: {}, uk: {} },
    },
    {
        id: 'doc2',
        title: 'Каталог ArmoPlit 2027',
        categoryKey: 'categories.armoplit',
        updatedAt: new Date('2024-01-15'),
        tags: ['Каталог', 'ArmoPlit'],
        content: { en: {}, uk: {} },
    },
    {
        id: 'doc3',
        title: 'Сертифікат відповідності. 2025-2026',
        categoryKey: 'categories.armoplit',
        updatedAt: new Date('2024-03-10'),
        tags: ['Сертифікат відповідності', 'ArmoPlit'],
        content: { en: {}, uk: {} },
    },
    {
        id: 'doc4',
        title: 'ТЕХНІЧНИЙ ЛИСТ ArmoPlit',
        categoryKey: 'categories.armoplit',
        updatedAt: new Date('2023-11-20'),
        tags: ['Технічний лист', 'ArmoPlit'],
        content: { en: {}, uk: {} },
    },
    {
        id: 'doc5',
        title: 'Laviosa. Сертифікат відповідності. 2025-2026',
        categoryKey: 'categories.edilmodulo',
        updatedAt: new Date('2024-02-28'),
        tags: ['Сертифікат відповідності', 'Laviosa'],
        content: { en: {}, uk: {} },
    },
    {
        id: 'doc6',
        title: 'booklet Edilmodulo 210x297 mm Preview',
        categoryKey: 'categories.edilmodulo',
        updatedAt: new Date('2023-12-05'),
        tags: ['Каталог', 'Edilmodulo'],
        content: { en: {}, uk: {} },
    },
    {
        id: 'doc7',
        title: 'ТЕХНІЧНИЙ ЛИСТ Edilmodulo',
        categoryKey: 'categories.edilmodulo',
        updatedAt: new Date('2023-12-01'),
        tags: ['Технічний лист', 'Edilmodulo'],
        content: { en: {}, uk: {} },
    },
    {
        id: 'doc8',
        title: 'JUTA. Висновок СЕЕ на стрічки М-1, М-2, У-1, UNI 2025 - 2028',
        categoryKey: 'categories.fixit',
        updatedAt: new Date('2024-01-20'),
        tags: ['Висновок СЕЕ', 'JUTA', 'Стрічки'],
        content: { en: {}, uk: {} },
    },
     {
        id: 'doc9',
        title: 'FREUDENBERG. Сертифікат відповідності на Enkamat, Enkadrain, Colbonddrain. 2025-2026.',
        categoryKey: 'categories.freudenberg',
        updatedAt: new Date('2024-03-25'),
        tags: ['Сертифікат відповідності', 'Enkamat', 'Enkadrain', 'Colbonddrain'],
        content: { en: {}, uk: {} },
    },
    {
        id: 'doc10',
        title: 'DuPont. Сертифікат відповідності на Typar. 2024-2027',
        categoryKey: 'categories.typar',
        updatedAt: new Date('2024-04-12'),
        tags: ['Сертифікат відповідності', 'Typar', 'DuPont'],
        content: { en: {}, uk: {} },
    },
    {
        id: 'doc11',
        title: 'Каталог Typar SF 2025',
        categoryKey: 'categories.typar',
        updatedAt: new Date('2024-02-18'),
        tags: ['Каталог', 'Typar SF'],
        content: { en: {}, uk: {} },
    },
    {
        id: 'doc12',
        title: 'Рекомендації по підбору геотекстилів',
        categoryKey: 'categories.typar',
        updatedAt: new Date('2023-11-30'),
        tags: ['Рекомендації', 'Геотекстиль'],
        content: { en: {}, uk: {} },
    },
];